// This is a file generated by the yeoman generator hapijs

/**
 * All the endpoints for anything related to link
 *
 * @type {exports}
 */
var Joi = require('joi');
var linkController = require('./link-ctrl');

module.exports = function() {
  return [
    {
      method: 'POST',
      path: '/links',
      config: {
        description: 'Creates a link',
        handler: linkController.create,
        validate: {
          payload: {
            // TODO: Add some validations
          }
        }
      }
    },
		
    {
      method: 'GET',
      path: '/links',
      config : {
        description: 'Fetches all links',
        handler: linkController.find
      }
    },
		
    {
      method: 'GET',
      path: '/links/{id}',
      config : {
        description: 'Fetches a link by id',
        handler: linkController.findById,
        validate: {
          params: {
            id: Joi.number().integer().required()
          }
        }
      }
    },
		
    {
      method: 'PUT',
      path: '/links/{id}',
      config : {
        description: 'Updates a link for a specific id',
        handler: linkController.update,
        validate: {
          params: {
            id: Joi.number().integer().required()
          },
          payload: {
            // TODO: Add some validations
          }
        }
      }
    },
		
    {
      method: 'DELETE',
      path: '/links/{id}',
      config : {
        description: 'Remove a link for a specific id',
        handler: linkController.remove,
        validate: {
          params: {
            id: Joi.number().integer().required()
          }
        }
      }
    }
		
		/* Add new methods above */
  ]
}();
