// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets link from the datastore
 *
 * @type {exports}
 */
var Mongoose = require('mongoose');
var Joi = require('joi');

var linkSchema = new Mongoose.Schema({
  _id : Mongoose.Schema.Types.ObjectId,
  file_id:  Mongoose.Schema.Types.ObjectId,
  path: String,
  status : String,
  created_date: {
  	type: Date,
  	default: Date.now
  },
  expires_at: {
  	type: Date 
  }
});

module.exports = Mongoose.model('Link', linkSchema)