// This is a file generated by the yeoman generator hapijs

/**
 * Controller which handles requests/responses relating to link
 *
 * @type {linkDao|exports}
 */
var linkDao = require('./link-dao');
var Boom = require('boom');

/**
 * Creates a link
 *
 * @param req
 * @param reply
 */
exports.create = function (req, reply) {

	linkDao.create(req.payload, function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};

/**
 * Gets all links
 *
 * @param req
 * @param reply
 */
exports.find = function (req, reply) {

	linkDao.find(function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};

/**
 * Get a specific link by id
 *
 * @param req
 * @param reply
 */
exports.findById = function (req, reply) {

	linkDao.findById(req.params.id, function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};

/**
 * Update a specific link by id
 *
 * @param req
 * @param reply
 */
exports.update = function (req, reply) {

	linkDao.update(req.params.id, req.payload, function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};
		
/**
 * Remove a specific link by id
 *
 * @param req
 * @param reply
 */
exports.remove = function (req, reply) {

	linkDao.remove(req.params.id, function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};

/* Add new methods above */
