// This is a file generated by the yeoman generator hapijs

/**
 * All the endpoints for anything related to auth
 *
 * @type {exports}
 */
var Joi = require('joi'),
  authController = require('./auth-ctrl');

module.exports = function() {
  return [
    {
      method: 'POST',
      path: '/users',
      config: {
        description: 'Create a new user',
        handler: authController.createUser,
        validate: {
          payload: {
            firstname: Joi.string().required(),
            lastname: Joi.string().required(),
            password: Joi.string().required(),
            email: Joi.string().required()
          }
        }
      }
    },
    {
      method: 'DELETE',
      path: '/users/{_id}',
      config: {
        description: 'Delete a user',
        handler: authController.deleteUser,
        auth: {
          strategies: ['token']
        }
      }
    },
    {
      method: 'POST',
      path: '/login',
      config: {
        description: 'Authenticate a user and give him a token.',
        handler: authController.login,
        validate: {
          payload: {
            email: Joi.string().required(),
            password: Joi.string().required()
          }
        }
      }
    },
    {
      method: 'GET',
      path: '/logout',
      config: {
        description: 'Revoke access to a token by dumping it into redis',
        handler: authController.logout,
        auth: {
          strategies: ['token']
        }
      }
    },
    {
      method: 'POST',
      path: '/token',
      config: {
        description: 'Give the user a new token.',
        handler: authController.token,
        validate: {
          payload: {
            token: Joi.string().required()
          }
        }
      }
    },
    {
      method: 'GET',
      path: '/test',
      config: {
        description: 'This is just a test endpoint.',
        handler: authController.test,
        auth: {
          strategies: ['token']
        }
      }
    }
  ]
}();
