// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets file from the datastore
 *
 * @type {exports}
 */
var Boom = require('boom');
var Mongoose = require('mongoose');

var historySchema = new Mongoose.Schema({
  app : Object,
  auth : Object,
  headers : Object,
  info : Object,
  method : String,
  mime : String,
  orig : Object,
  params : Object,
  paramsArray : Array,
  _logger: Array,
  path : String,
  payload : Object,
  query : Object,
  state : Object,
  url : Object,
  response: Object
});

module.exports = Mongoose.model('History', historySchema, 'history')