// This is a file generated by the yeoman generator hapijs

/**
 * All the endpoints for anything related to upload
 *
 * @type {exports}
 */
var Joi = require('joi');
var uploadController = require('./upload-ctrl');
var Wreck = require('wreck');
var Boom = require('boom');

module.exports = function() {
  return [

    {
      method: 'POST',
      path: '/upload',
      handler: {
        proxy: {
          uri: 'http://localhost:6543/upload',
          onResponse: function(err, res, request, reply, settings, ttl){
            Wreck.read(res, {json : true}, function (err, response) {
               if(err){

               }
               reply(JSON.stringify(response));
            });
          },
          passThrough: true,
          xforward: false
        }
      },
      config:{
        auth: {
          strategies: ['token']
        },
        payload : {
          maxBytes : 1048576 * 10
        }        
      }
    }

  ]
}();
