// This is a file generated by the yeoman generator hapijs

/**
 * Controller which handles requests/responses relating to auth
 *
 * @type {authDao|exports}
 */
//var apictrl = require('../api-plugins/api-ctrl');
	

/**
 * Gets all auths
 *
 * @param req
 * @param reply
 */
exports.controller = function (request, reply) {
	/*authDao.find(function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
*/
	//apictrl.controller(request.params,reply);
};
