// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets file from the datastore
 *
 * @type {exports}
 */
var Boom = require('boom');
var Mongoose = require('mongoose');
var Joi = require('joi');

var fileSchema = new Mongoose.Schema({
  _id : Mongoose.Schema.Types.ObjectId,
  path: String,
  metadata_path: String,
  data_path: String,
  file_name: String
});

module.exports = Mongoose.model('Nodes', fileSchema)