// This is a file generated by the yeoman generator hapijs

/**
 * All the endpoints for anything related to file
 *
 * @type {exports}
 */
var Joi = require('joi');
var fileController = require('./file-ctrl');

module.exports = function() {
  return [
		
    {
      method: 'GET',
      path: '/files/{path*}',
      config : {
        auth: {
          strategies: ['token']
        },
        description: 'Fetches a file by id',
        handler: fileController.findByPath,
        validate: {
          params: {
            path: Joi.string().required()
          }
        },
        plugins:{
          'sc-limits' : {
            rate_limits : [
              {
                period: 10,
                limit: 50
              },
              {
                period: 60,
                limit: 50
              },

              {
                period: 1440,
                limit: 100
              }
            ]
          }
        },
      }
    },
		
		/* Add new methods above */
  ]
}();