// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets browse from the datastore
 *
 * @type {exports}
 */
var Boom = require('boom');

/**
 * Creates a browse
 *
 * @param payload - The data to be used to create a browse
 * @param callback
 */
exports.create = function (payload, callback) {
	// TODO: Implement dao method and call callback(null, <data>)
	return callback(Boom.notImplemented());
};
